#!/usr/bin/env python3
"""Wave 0 unit tests — Document Re-Hydration & Provenance Reuse.

Covers T0a (HAR capture at CrawlerEngine.crawl), T0b (document_data schema +
har_path/sources persistence), T0c (SourceRegistry.penalize_url wiring), and
T0d (graceful degradation + structured logging) without touching the live web.

Run:  pytest backend/tests/unit/test_document_rehydration_wave0.py -q
"""
import asyncio
import json
import os
import sqlite3
import sys
import unittest.mock as mock

REPO_ROOT = r"C:\dev\IRISVOICE"
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from backend.crawler.crawler_engine import CrawlerEngine, CrawlResult
from backend.agent.document_store import DocumentDataStore
from backend.crawler.source_registry import SourceRegistry, get_source_registry
from backend.crawler.orchestrator import CrawlOrchestrator


# ── Fakes ──────────────────────────────────────────────────────────────────
class FakeRobots:
    def __init__(self, allowed=True):
        self._allowed = allowed

    async def is_allowed(self, url, ua):
        return self._allowed


class FakeResult:
    def __init__(self, status_code=200, response_headers=None, markdown="",
                 html=None, metadata=None):
        self.status_code = status_code
        self.response_headers = response_headers or {}
        self.markdown = markdown
        self.html = html
        self.metadata = metadata or {}


class FakeCrawler:
    def __init__(self, results):
        self._results = list(results)
        self._i = 0

    async def arun(self, url, config):
        if self._i >= len(self._results):
            raise IndexError("no more fake results")
        r = self._results[self._i]
        self._i += 1
        return r


# ── T0a: HAR capture at the per-request layer ──────────────────────────────
def test_t0a_har_entry_captured_with_correct_fields():
    engine = CrawlerEngine()
    engine._crawler = FakeCrawler([
        FakeResult(200, {"content-type": "text/html"}, "# Title\nbody text", None, {"title": "Title"}),
    ])
    with mock.patch("backend.crawler.crawler_engine.get_robots_checker",
                   return_value=FakeRobots(allowed=True)):
        result = asyncio.run(engine.crawl(
            query="q", urls=["http://example.com/a"], instructions="", job_id="job123"))

    assert len(result.har_entries) == 1, result.har_entries
    e = result.har_entries[0]
    assert e["url"] == "http://example.com/a"
    assert e["method"] == "GET"
    assert e["status"] == 200
    assert e["response_headers"] == {"content-type": "text/html"}
    assert e["content_length"] == len("# Title\nbody text")
    assert isinstance(e["body_sha256"], str) and len(e["body_sha256"]) == 64
    assert e["duration_ms"] >= 0
    # File named by job_id and actually written
    assert result.har_path.endswith("job123.har"), result.har_path
    assert os.path.isfile(result.har_path)
    with open(result.har_path, "r", encoding="utf-8") as fh:
        written = json.load(fh)
    assert isinstance(written, list) and len(written) == 1
    assert written[0]["url"] == "http://example.com/a"
    # cleanup
    os.remove(result.har_path)


def test_t0a_robots_block_recorded_as_evidence():
    engine = CrawlerEngine()
    engine._crawler = FakeCrawler([FakeResult(200)])
    with mock.patch("backend.crawler.crawler_engine.get_robots_checker",
                   return_value=FakeRobots(allowed=False)):
        result = asyncio.run(engine.crawl(
            query="q", urls=["http://blocked.com/x"], instructions="", job_id="jobR"))

    assert result.har_entries[0]["status"] == "robots_blocked"
    assert result.pages[0].error == "blocked by robots.txt"
    if result.har_path and os.path.isfile(result.har_path):
        os.remove(result.har_path)


def test_t0a_fetch_exception_recorded_without_raising():
    engine = CrawlerEngine()
    engine._crawler = FakeCrawler([FakeResult(200)])
    # Force arun to raise by replacing it
    async def _boom(url, config):
        raise RuntimeError("connection reset")
    engine._crawler.arun = _boom
    with mock.patch("backend.crawler.crawler_engine.get_robots_checker",
                   return_value=FakeRobots(allowed=True)):
        result = asyncio.run(engine.crawl(
            query="q", urls=["http://example.com/y"], instructions="", job_id="jobE"))

    assert result.har_entries[0]["status"] is None
    assert "connection reset" in result.har_entries[0]["error"]
    assert result.pages[0].error == "connection reset"
    if result.har_path and os.path.isfile(result.har_path):
        os.remove(result.har_path)


def test_t0a_job_id_autogenerated_when_missing():
    engine = CrawlerEngine()
    engine._crawler = FakeCrawler([FakeResult(200)])
    with mock.patch("backend.crawler.crawler_engine.get_robots_checker",
                   return_value=FakeRobots(allowed=True)):
        result = asyncio.run(engine.crawl(
            query="q", urls=["http://example.com/z"], instructions=""))
    assert result.har_path and os.path.isfile(result.har_path)
    os.remove(result.har_path)


# ── T0b: document_data schema + har_path/sources persistence ───────────────
def test_t0b_alter_table_idempotent_and_columns_present():
    conn = sqlite3.connect(":memory:")
    store = DocumentDataStore(conn)
    store._ensure_table()          # first run
    store._ensure_table()          # second run must be a safe no-op
    cols = {r[1] for r in conn.execute("PRAGMA table_info(document_data)").fetchall()}
    for col in ("source_document_id", "sources", "har_path"):
        assert col in cols, f"missing column {col}"


def test_t0b_store_and_get_persist_provenance():
    conn = sqlite3.connect(":memory:")
    store = DocumentDataStore(conn)
    store.store(
        "d1", "c1", "json", "{}", {}, [], "trusted",
        source_document_id="d0",
        sources=[{"url": "http://x.com/a", "title": "A"}],
        har_path="data/har/job1.har",
    )
    got = store.get("d1")
    assert got["source_document_id"] == "d0"
    assert got["har_path"] == "data/har/job1.har"
    assert got["sources"] == [{"url": "http://x.com/a", "title": "A"}]


def test_t0b_store_defaults_keep_backward_compat():
    conn = sqlite3.connect(":memory:")
    store = DocumentDataStore(conn)
    # Old callers pass no provenance fields — must still succeed.
    store.store("d2", "c2", "markdown", "hi", {}, [], "trusted")
    got = store.get("d2")
    assert got["source_document_id"] is None
    assert got["har_path"] is None
    assert got["sources"] == []


# ── T0c: SourceRegistry.penalize_url (reused, not reinvented) ──────────────
def test_t0c_penalize_url_downweights_existing_entry():
    reg = SourceRegistry(store={})
    # Bypass LLM topic extraction for a deterministic topic (async method).
    reg._extract_topics = mock.AsyncMock(return_value=["ai hardware"])  # type: ignore[assignment]
    item = type("Item", (), {"url": "http://dead.com/x"})()
    sr = type("SR", (), {"results": [item]})()
    asyncio.run(reg.learn("ai hardware", sr, credibility_map={"dead.com": 0.8}))
    before = json.loads(reg._get_store("topic:ai_hardware"))
    before_cred = [e for e in before if e["url"] == "http://dead.com/x"][0]["credibility"]
    assert before_cred == 0.8

    reg.penalize_url("http://dead.com/x", topics=["ai hardware"])
    after = json.loads(reg._get_store("topic:ai_hardware"))
    after_cred = [e for e in after if e["url"] == "http://dead.com/x"][0]["credibility"]
    assert after_cred == round(0.8 * 0.5, 3)
    # Use case preserved: resolve/learn still function.
    res = asyncio.run(reg.resolve("ai hardware"))
    assert "sources" in res and "coverage_score" in res


def test_t0c_orchestrator_applies_penalty_for_dead_status():
    fake = type("FakeReg", (), {"calls": []})()
    def _pen(url, topics):
        fake.calls.append((url, topics))
    fake.penalize_url = _pen
    with mock.patch("backend.crawler.source_registry.get_source_registry",
                    return_value=fake):
        orch = CrawlOrchestrator()
        res = CrawlResult(
            query="q", pages=[], duration_ms=0, crawled_at="",
            har_entries=[{"url": "http://dead.com/x", "status": 404, "error": ""}],
        )
        orch._apply_har_penalties(res, "q")
    assert fake.calls == [("http://dead.com/x", ["q"])]


def test_t0c_orchestrator_skips_healthy_status():
    fake = type("FakeReg", (), {"calls": []})()
    fake.penalize_url = lambda url, topics: fake.calls.append((url, topics))
    with mock.patch("backend.crawler.source_registry.get_source_registry",
                    return_value=fake):
        orch = CrawlOrchestrator()
        res = CrawlResult(
            query="q", pages=[], duration_ms=0, crawled_at="",
            har_entries=[{"url": "http://ok.com", "status": 200, "error": ""}],
        )
        orch._apply_har_penalties(res, "q")
    assert fake.calls == []


# ── T0d: graceful degradation (no path raises into caller) ─────────────────
def test_t0d_har_write_failure_degrades_to_none():
    import tempfile as _tf

    # Make _har_dir point at an existing FILE so os.makedirs() fails *inside*
    # _write_har_file's own try/except — the real graceful path returns None.
    tmpf = _tf.NamedTemporaryFile(delete=False)
    tmpf.close()
    try:
        with mock.patch("backend.crawler.crawler_engine._har_dir",
                        return_value=tmpf.name):
            # The helper itself must not raise and must return None.
            path = __import__("backend.crawler.crawler_engine",
                              fromlist=["_write_har_file"])._write_har_file(
                "jobX", [{"url": "u"}])
            assert path is None
            # And crawl() must still return pages with har_path=None.
            engine = CrawlerEngine()
            engine._crawler = FakeCrawler([FakeResult(200)])
            with mock.patch("backend.crawler.crawler_engine.get_robots_checker",
                           return_value=FakeRobots(allowed=True)):
                result = asyncio.run(engine.crawl(
                    query="q", urls=["http://example.com/a"],
                    instructions="", job_id="jobX"))
            assert result.har_path is None
            assert len(result.pages) == 1
    finally:
        os.remove(tmpf.name)


def test_t0d_penalize_failure_does_not_raise():
    fake = type("FakeReg", (), {})()
    def _boom(url, topics):
        raise RuntimeError("registry down")
    fake.penalize_url = _boom
    with mock.patch("backend.crawler.source_registry.get_source_registry",
                    return_value=fake):
        orch = CrawlOrchestrator()
        res = CrawlResult(
            query="q", pages=[], duration_ms=0, crawled_at="",
            har_entries=[{"url": "http://dead.com/x", "status": 404, "error": ""}],
        )
        # Must not raise despite penalize_url blowing up.
        orch._apply_har_penalties(res, "q")


def test_t0d_finalize_carries_har_fields():
    orch = CrawlOrchestrator()
    fetched = CrawlResult(
        query="q", pages=[], duration_ms=5, crawled_at="",
        har_entries=[{"url": "u", "status": 200}], har_path="data/har/j.har")
    out = orch._finalize(fetched, "q", __import__("time").monotonic())
    assert out.har_path == "data/har/j.har"
    assert out.har_entries == [{"url": "u", "status": 200}]
