// GENERATED by scripts/gen_turn_protocol_ts.py from backend/agent/turn_protocol.py.
// Do not edit by hand: change the Python SCHEMA and re-run the generator.
// The contract test (backend/tests/contract/test_turn_protocol_contract.py) fails when this file is stale.

export const TURN_PROTOCOL_VERSION = 1

export type TurnStatus = 'ok' | 'error' | 'cancelled'

export interface TurnStartPayload {
  v: number
  turn_id: string
  conversation_id: string
  strand_id: string
  author: string
  to: string[]
  refs: string[]
  mode: string
  prompt: string
  client_ref?: string
  ts: number
}

export interface TextPart {
  type: 'text'
  delta: string
}

export interface ReasoningPart {
  type: 'reasoning'
  delta: string
}

export interface ToolCallPart {
  type: 'tool_call'
  name: string
  call_id?: string
  data: Record<string, unknown>
}

export interface ToolResultPart {
  type: 'tool_result'
  name: string
  call_id?: string
  ok: boolean
  data: Record<string, unknown>
}

export interface TodoPart {
  type: 'todo'
  event: string
  data: Record<string, unknown>
}

export interface CardPart {
  type: 'card'
  data: Record<string, unknown>
}

export interface InteractionPart {
  type: 'interaction'
  event: string
  data: Record<string, unknown>
}

export interface NoticePart {
  type: 'notice'
  event: string
  message: string
  data: Record<string, unknown>
}

export interface ErrorPart {
  type: 'error'
  code: string
  message: string
  recoverable: boolean
}

export type TurnPart =
  | TextPart
  | ReasoningPart
  | ToolCallPart
  | ToolResultPart
  | TodoPart
  | CardPart
  | InteractionPart
  | NoticePart
  | ErrorPart

export const TURN_PART_TYPES = ['text', 'reasoning', 'tool_call', 'tool_result', 'todo', 'card', 'interaction', 'notice', 'error'] as const

export interface TurnPartPayload {
  v: number
  turn_id: string
  conversation_id: string
  seq: number
  ts: number
  part: TurnPart
}

export interface TurnEndPayload {
  v: number
  turn_id: string
  conversation_id: string
  parts: number
  text: string
  speak: string
  error?: string
  ts: number
  status: TurnStatus
}

export type TurnMessage =
  | { type: 'turn.start'; payload: TurnStartPayload }
  | { type: 'turn.part'; payload: TurnPartPayload }
  | { type: 'turn.end'; payload: TurnEndPayload }
