// === ACTION VERB REGISTRY (REQ-14) ===
// ONE place that maps a backend tool name to the short verb shown on a task
// card / CLI block. Both the GUI card (T9) and the CLI renderer (T12) import
// `resolveVerb` from here — neither one is allowed to know a tool name.
//
// Source of truth for the tool list: `backend/agent/tool_registry.py`
// (52 tools as of 2026-08-19; see `__tests__/cards/__fixtures__/tool_registry_snapshot.json`,
// regenerated by `scripts/gen_tool_registry_fixture.py`).
//
// AC6 (REQ-14): a verb is added, changed or removed by editing THIS FILE
// alone — never a card, never a renderer.

/** The 26 verbs in the vocabulary, grouped by family. Every verb is <=6
 *  characters and a real word (never an acronym, never a truncation) — AC2.
 *  This is the source the CT-6 test iterates, so a future verb that breaks
 *  the 6-char ceiling fails here rather than being clipped at render time. */
export const VERBS_BY_FAMILY = {
  io: ["READ", "WRITE", "PATCH", "LIST", "ERASE"],
  exec: ["EXEC"],
  vcs: ["DIFF", "COMMIT", "PUSH", "BRANCH", "LOG"],
  forge: ["FORGE"],
  web: ["SEARCH", "FETCH"],
  vision: ["SEE", "SNAP"],
  gui: ["CLICK", "TYPE", "KEY"],
  media: ["CLIP", "SCRIBE", "MERGE"],
  memory: ["RECALL", "LEARN", "PACK"],
  dialog: ["ASK", "SPEAK"],
} as const

export type Family = keyof typeof VERBS_BY_FAMILY
export type Verb = (typeof VERBS_BY_FAMILY)[Family][number]

/** Flattened for iteration — every verb across every family, in one place. */
export const ALL_VERBS: Verb[] = Object.values(VERBS_BY_FAMILY).flat() as Verb[]

// ── Tier 1 — per-tool assignment (AC1, AC4) ─────────────────────────────────
// Every tool registered in tool_registry.py gets an explicit verb here. Two
// tools may share a verb (allowed by design — the target text disambiguates).
export const TOOL_VERB: Record<string, Verb> = {
  // io — file (5)
  read_file: "READ",
  write_file: "WRITE",
  list_directory: "LIST",
  create_directory: "WRITE",
  // ERASE was added to the io family 2026-08-19 (27th verb). The original 26
  // did not cover deletion, and PATCH — "mutate existing state" — UNDERSTATES a
  // destructive action. The card is the user's record of what the agent did, so
  // the one case where the verb must not be softened is the destructive one.
  // Consistent with delete_file being ALWAYS_ASK under REQ-19: the permission
  // layer treats it as the most dangerous class, and the label must agree.
  // ERASE: 5 chars, a real word, no acronym, no truncation — obeys REQ-14 AC2.
  delete_file: "ERASE",

  // exec — app (2) + shell (1) + system control (3)
  launch_app: "EXEC",
  open_file: "EXEC",
  run_command: "EXEC",
  lock_screen: "EXEC",
  restart: "EXEC",
  shutdown: "EXEC",

  // vcs — git (7)
  // git_status has no literal "status" verb; it is the closest live relative
  // of git_diff (both report the working tree's current change state), so it
  // shares DIFF rather than borrowing LOG (commit history) or BRANCH.
  git_status: "DIFF",
  git_diff: "DIFF",
  git_log: "LOG",
  git_commit: "COMMIT",
  git_create_branch: "BRANCH",
  git_checkout: "BRANCH",
  git_push: "PUSH",

  // forge — github (7). These are GitHub-API account/repo management, not
  // local git operations, which is exactly the "forge" family's job — one
  // verb for the whole platform surface, the target text disambiguates.
  github_get_user: "FORGE",
  github_list_repos: "FORGE",
  github_get_repo_branches: "FORGE",
  github_generate_ssh_key: "FORGE",
  github_list_ssh_keys: "FORGE",
  github_delete_ssh_key: "FORGE",
  github_connect_pat: "FORGE",

  // gui — gui_automation MCP (2) + legacy "web"-categorized gui ops (3)
  gui_automate_click: "CLICK",
  gui_automate_type: "TYPE",
  gui_click: "CLICK",
  gui_type: "TYPE",
  gui_press_key: "KEY",

  // web — search/fetch (also covers the "search" tool's aliases below)
  crawler_query: "SEARCH",
  open_url: "FETCH",
  search: "SEARCH",
  web_search: "SEARCH", // alias of "search"
  google_search: "SEARCH", // alias of "search"

  // vision — vision.* MCP (4) + screen capture (3)
  vision_detect_element: "SEE",
  vision_analyze_screen: "SEE",
  vision_validate_action: "SEE",
  vision_get_context: "SEE",
  take_screenshot: "SNAP",
  screenshot_page: "SNAP",
  start_screen_monitor: "SEE",

  // media (3)
  clip_video: "CLIP",
  transcribe_media: "SCRIBE",
  // Aggregates multiple per-frame analyses into one summary -> MERGE.
  analyze_video_frames: "MERGE",

  // memory — memory (4) + research (1, self-improvement is a LEARN op) +
  // create_skill (system category, but it teaches the agent a new skill).
  recall_memory: "RECALL",
  get_rendered_documents: "RECALL",
  list_conversations: "RECALL",
  combine_documents: "PACK",
  improve_self: "LEARN",
  create_skill: "LEARN",
  get_system_info: "READ",

  // dialog — system (2)
  ask_user_question: "ASK",
  speak: "SPEAK",
}

// ── Tier 2 — family fallback (AC5) ──────────────────────────────────────────
// One default verb per family, used ONLY when a tool name is not in TOOL_VERB
// above. Kept as DATA (not a switch) so a future family or a changed default
// is a one-line edit.
export const FAMILY_FALLBACK_VERB: Record<Family, Verb> = {
  io: "READ",
  exec: "EXEC",
  vcs: "LOG",
  forge: "FORGE",
  web: "FETCH",
  vision: "SEE",
  gui: "CLICK",
  media: "SCRIBE",
  memory: "RECALL",
  dialog: "SPEAK",
}

/** Ordered prefix rules mapping an UNREGISTERED tool name to its family, so a
 *  brand-new tool that follows the existing naming convention (e.g. a future
 *  `git_stash`, `vision_read_pixel`, `github_list_orgs`) still lands on a
 *  sensible verb instead of the raw-name fallback. First match wins. Data,
 *  not a switch — extending family coverage is a new row here. */
export const FAMILY_PREFIX_RULES: ReadonlyArray<{ prefix: string; family: Family }> = [
  { prefix: "github_", family: "forge" },
  { prefix: "git_", family: "vcs" },
  { prefix: "vision_", family: "vision" },
  { prefix: "gui_", family: "gui" },
  { prefix: "web_", family: "web" },
  { prefix: "read_", family: "io" },
  { prefix: "write_", family: "io" },
  { prefix: "list_", family: "io" },
  { prefix: "create_", family: "io" },
  { prefix: "delete_", family: "io" },
  { prefix: "recall_", family: "memory" },
  { prefix: "memory_", family: "memory" },
  { prefix: "ask_", family: "dialog" },
  { prefix: "speak", family: "dialog" },
  { prefix: "run_", family: "exec" },
  { prefix: "launch_", family: "exec" },
  { prefix: "transcribe_", family: "media" },
  { prefix: "clip_", family: "media" },
  { prefix: "analyze_video", family: "media" },
]

/**
 * Resolve a tool name to its display verb. Resolution order (AC5):
 *   1. registry  — exact match in TOOL_VERB
 *   2. family    — prefix match in FAMILY_PREFIX_RULES -> FAMILY_FALLBACK_VERB
 *   3. compact   — the raw name, abbreviated to FIT THE VERB COLUMN
 *                  (session 246, user-directed amendment to AC2: unregistered
 *                  MCP/custom tools used to render their full uppercased name
 *                  and overflow the fixed-width column; they now compact to
 *                  <=6 chars via first-segment / acronym / hard-slice)
 *
 * Both the GUI card and the CLI renderer call this ONE function.
 */
export const VERB_MAX_CHARS = 6

function compactVerb(raw: string): string {
  const up = raw.toUpperCase().trim()
  if (up.length <= VERB_MAX_CHARS) return up
  // Multi-part names (notion_search, fetch.crawl, github_list_orgs):
  // prefer the FIRST SEGMENT when it already fits ("notion_search" ->
  // "NOTION"), else the acronym of all segments ("database_query_page" ->
  // "DQP"), else a hard slice.
  const parts = up.split(/[_\-.:]+/).filter(Boolean)
  if (parts.length > 1) {
    if (parts[0].length <= VERB_MAX_CHARS && parts[0].length >= 3) return parts[0]
    const acro = parts.map((p) => p[0]).join("")
    if (acro.length >= 2 && acro.length <= VERB_MAX_CHARS) return acro
  }
  return up.slice(0, VERB_MAX_CHARS)
}

export function resolveVerb(toolName: string | null | undefined): string {
  if (!toolName) return "TOOL"

  const direct = TOOL_VERB[toolName]
  if (direct) return direct

  const rule = FAMILY_PREFIX_RULES.find((r) => toolName.startsWith(r.prefix))
  if (rule) return FAMILY_FALLBACK_VERB[rule.family]

  return compactVerb(toolName)
}
