@echo off
echo Cleaning up lock files...
if exist "dist\dev\lock" del "dist\dev\lock"
echo.
echo Clearing Next.js cache...
if exist "dist" rmdir /s /q "dist"
if exist ".next" rmdir /s /q ".next"
echo.
echo Starting IRIS Backend...
start "IRIS Backend" cmd /k "C:\Python313\python.exe start-backend.py"
echo.
echo Starting IRIS Widget (Tauri + Next.js)...
npm run dev:tauri
