"""Generate lib/turns/protocol.ts from backend/agent/turn_protocol.py SCHEMA.

    python scripts/gen_turn_protocol_ts.py          # write the file
    python scripts/gen_turn_protocol_ts.py --check  # exit 1 when it is stale

The Python schema is the single source of truth (execution audit, Phase 3:
"The schema lives in one Python module, and the TypeScript types are
generated from it"). The module is loaded by FILE PATH so generating never
imports the agent package (backend/agent/__init__.py pulls in the kernel).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "backend" / "agent" / "turn_protocol.py"
OUT = ROOT / "lib" / "turns" / "protocol.ts"

_TS = {"string": "string", "number": "number", "boolean": "boolean", "string[]": "string[]", "json": "Record<string, unknown>"}


def load_schema() -> dict:
    spec = importlib.util.spec_from_file_location("_turn_protocol_for_gen", SRC)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod.SCHEMA


def _fields(spec: dict, indent: str = "  ") -> str:
    lines = []
    for name, typ in spec.items():
        optional = typ.endswith("?")
        base = typ.rstrip("?")
        if base not in _TS:
            raise ValueError(f"unknown schema type {typ!r} for field {name!r}")
        lines.append(f"{indent}{name}{'?' if optional else ''}: {_TS[base]}")
    return "\n".join(lines)


def _pascal(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


def render(schema: dict) -> str:
    parts = schema["parts"]
    out = [
        "// GENERATED by scripts/gen_turn_protocol_ts.py from backend/agent/turn_protocol.py.",
        "// Do not edit by hand: change the Python SCHEMA and re-run the generator.",
        "// The contract test (backend/tests/contract/test_turn_protocol_contract.py) fails when this file is stale.",
        "",
        f"export const TURN_PROTOCOL_VERSION = {int(schema['version'])}",
        "",
        "export type TurnStatus = 'ok' | 'error' | 'cancelled'",
        "",
        "export interface TurnStartPayload {",
        _fields(schema["start"]),
        "}",
        "",
    ]
    names = []
    for ptype, spec in parts.items():
        iname = f"{_pascal(ptype)}Part"
        names.append(iname)
        out += [f"export interface {iname} {{", f"  type: '{ptype}'"]
        if spec:
            out.append(_fields(spec))
        out += ["}", ""]
    out += [
        f"export type TurnPart =\n  | " + "\n  | ".join(names),
        "",
        f"export const TURN_PART_TYPES = [{', '.join(repr(p) for p in parts)}] as const",
        "",
        "export interface TurnPartPayload {",
        _fields(schema["part_envelope"]),
        "  part: TurnPart",
        "}",
        "",
        "export interface TurnEndPayload {",
        _fields({k: v for k, v in schema["end"].items() if k != "status"}),
        "  status: TurnStatus",
        "}",
        "",
        "export type TurnMessage =",
        "  | { type: 'turn.start'; payload: TurnStartPayload }",
        "  | { type: 'turn.part'; payload: TurnPartPayload }",
        "  | { type: 'turn.end'; payload: TurnEndPayload }",
        "",
    ]
    return "\n".join(out)


def main(argv: list) -> int:
    text = render(load_schema())
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run python scripts/gen_turn_protocol_ts.py")
            return 1
        print("turn protocol types are current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
